########################
# XVAULTS CONFIG FILE #
########################
#
# XVaults Developed by Beckstation
#
# This plugin does not currently have configuration options.
# This config will serve as the save for players vaults and items.
# 
# Any questions, please join the XPlugins discord found on our spigot page. 
# Enjoy!
